In [24]:
import scipy.io.idl as idl
import numpy as np
from scipy.interpolate import griddata
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

In [143]:
from scipy.spatial import ConvexHull, Delaunay
from scipy.interpolate import griddata

# Linearly interpolate $B_x$ at single timepoint in 3D

In [174]:
data_path = '../../comprehensive_3d_plot/output/2016-04-07/'
data_ending = '.sav'

bz_z249_file = data_path + 'bz_z249' + data_ending
bz_z302_file = data_path + 'bz_z302' + data_ending
bz_z357_file = data_path + 'bz_z357' + data_ending
bz_z416_file = data_path + 'bz_z416' + data_ending

bz_z249_measurements = idl.readsav(bz_z249_file)
bz_z302_measurements = idl.readsav(bz_z302_file)
bz_z357_measurements = idl.readsav(bz_z357_file)
bz_z416_measurements = idl.readsav(bz_z416_file)

measurements = {0.249: bz_z249_measurements, 
                0.302: bz_z302_measurements, 
                0.357: bz_z357_measurements, 
                0.416: bz_z416_measurements}

z_planes = [0.249, 0.302, 0.357, 0.416]

# First generate grid in convex Hull of measurement points

In [158]:
time_point = 0
x_points = np.empty((0))
y_points = np.empty((0))
z_points = np.empty((0))
values = np.empty((0))
for z_plane in z_planes:
    plane_measurements = measurements[z_plane]
    x_points = np.append(x_points, plane_measurements['x_out'])
    y_points = np.append(y_points, plane_measurements['y_out'])
    z_points = np.append(z_points, np.ones(plane_measurements['x_out'].size)*z_plane)
    values = np.append(values, plane_measurements['a_out'][time_point])
    
    
points = [x_points, y_points, z_points]
points = np.asarray(points)

In [159]:
points = np.swapaxes(points, 0, 1)

In [160]:
points.shape

(4562, 3)

In [161]:
values.shape

(4562,)

In [163]:
x_min, x_max = points[:, 0].min(), points[:, 0].max() 
y_min, y_max = points[:, 1].min(), points[:, 1].max() 
z_min, z_max = points[:, 2].min(), points[:, 2].max() 
spatial_increment = 0.003

x_coord = np.linspace(x_min, x_max, np.ceil((x_max-x_min)/spatial_increment))
y_coord = np.linspace(y_min, y_max, np.ceil((y_max-y_min)/spatial_increment))
z_coord = np.linspace(z_min, z_max, np.ceil((z_max-z_min)/spatial_increment))

mesh = np.meshgrid(x_coord, y_coord, z_coord)

In [164]:
grid_points = np.dstack(map(np.ravel, mesh))[0]

In [165]:
grid_points.shape

(108360, 3)

In [166]:
grid_points[1,]

array([-0.087     , -0.085     ,  0.25203636])

In [167]:
in_convex_hull = bx_delaunay.find_simplex(grid_points)>=0

In [168]:
grid_points[in_convex_hull].shape

(56081, 3)

# Now interpolate inside convex hull

In [170]:
interpolated_data = griddata(points, values, grid_points[in_convex_hull])

In [ ]:
grid_points

# Repeat interpolation for all three components of vector and with function calls

In [204]:
data_path = '../../comprehensive_3d_plot/output/2016-04-07/'
data_ending = '.sav'

bx_z249_file = data_path + 'bx_z249' + data_ending
bx_z302_file = data_path + 'bx_z302' + data_ending
bx_z357_file = data_path + 'bx_z357' + data_ending
bx_z416_file = data_path + 'bx_z416' + data_ending

bx_z249_measurements = idl.readsav(bx_z249_file)
bx_z302_measurements = idl.readsav(bx_z302_file)
bx_z357_measurements = idl.readsav(bx_z357_file)
bx_z416_measurements = idl.readsav(bx_z416_file)

measurements_x = {0.249: bx_z249_measurements, 
                  0.302: bx_z302_measurements, 
                  0.357: bx_z357_measurements, 
                  0.416: bx_z416_measurements}

z_planes = [0.249, 0.302, 0.357, 0.416]

In [205]:
data_path = '../../comprehensive_3d_plot/output/2016-04-07/'
data_ending = '.sav'

by_z249_file = data_path + 'by_z249' + data_ending
by_z302_file = data_path + 'by_z302' + data_ending
by_z357_file = data_path + 'by_z357' + data_ending
by_z416_file = data_path + 'by_z416' + data_ending

by_z249_measurements = idl.readsav(by_z249_file)
by_z302_measurements = idl.readsav(by_z302_file)
by_z357_measurements = idl.readsav(by_z357_file)
by_z416_measurements = idl.readsav(by_z416_file)

measurements_y = {0.249: by_z249_measurements, 
                  0.302: by_z302_measurements, 
                  0.357: by_z357_measurements, 
                  0.416: by_z416_measurements}

z_planes = [0.249, 0.302, 0.357, 0.416]

In [206]:
data_path = '../../comprehensive_3d_plot/output/2016-04-07/'
data_ending = '.sav'

bz_z249_file = data_path + 'by_z249' + data_ending
bz_z302_file = data_path + 'by_z302' + data_ending
bz_z357_file = data_path + 'by_z357' + data_ending
bz_z416_file = data_path + 'by_z416' + data_ending

bz_z249_measurements = idl.readsav(bz_z249_file)
bz_z302_measurements = idl.readsav(bz_z302_file)
bz_z357_measurements = idl.readsav(bz_z357_file)
bz_z416_measurements = idl.readsav(bz_z416_file)

measurements_z = {0.249: bz_z249_measurements, 
                  0.302: bz_z302_measurements, 
                  0.357: bz_z357_measurements, 
                  0.416: bz_z416_measurements}

z_planes = [0.249, 0.302, 0.357, 0.416]

In [210]:
direction_measurements = [measurements_z, measurements_y, measurements_z] 

In [226]:
def read_points_from_measurement_dict(measurement_dict, time_point, z_planes):
    x_points = np.empty((0))
    y_points = np.empty((0))
    z_points = np.empty((0))
    values = np.empty((0))
    for z_plane in z_planes:
        plane_measurements = measurements[z_plane]
        x_points = np.append(x_points, plane_measurements['x_out'])
        y_points = np.append(y_points, plane_measurements['y_out'])
        z_points = np.append(z_points, np.ones(plane_measurements['x_out'].size)*z_plane)
        values = np.append(values, plane_measurements['a_out'][time_point])
    
    
    points = [x_points, y_points, z_points]
    points = np.asarray(points)
    points = np.swapaxes(points, 0, 1)
    return points, values

In [227]:
points = []
values = []
for measurements in direction_measurements:
    points_direction, values_direction = read_points_from_measurement_dict(measurement_dict, 0, z_planes)
    points.append(points_direction)
    values.append(values_direction)

In [228]:
def vector_measurement_bounds(vector_x_points, vector_y_points, vector_z_points):
    x_points = np.concatenate((np.concatenate((vector_x_points[0], vector_y_points[0])), 
                              vector_z_points[0]))
    y_points = np.concatenate((np.concatenate((vector_x_points[1], vector_y_points[1])),
                              vector_z_points[1]))
    z_points = np.concatenate((np.concatenate((vector_x_points[2], vector_y_points[2])),
                              vector_z_points[2]))
    x_min, x_max = x_points.min(), x_points.max() 
    y_min, y_max = y_points.min(), y_points.max()
    z_min, z_max = z_points.min(), z_points.max()
    return (x_min, x_max), (y_min, y_max), (z_min, z_max)

In [229]:
bounds = vector_measurement_bounds(points[0], points[1], points[2])

In [252]:
def mesh_bounded_by_convex_hulls(bounds, vector_points, spatial_increment):
    
    (x_min, x_max), (y_min, y_max), (z_min, z_max) = bounds
    
    x_delaunay = Delaunay(vector_points[0])
    y_delaunay = Delaunay(vector_points[1])
    z_delaunay = Delaunay(vector_points[2])
    
    x_coord = np.linspace(x_min, x_max, np.ceil((x_max-x_min)/spatial_increment))
    y_coord = np.linspace(y_min, y_max, np.ceil((y_max-y_min)/spatial_increment))
    z_coord = np.linspace(z_min, z_max, np.ceil((z_max-z_min)/spatial_increment))

    mesh = np.meshgrid(x_coord, y_coord, z_coord)
    
    grid_points = np.dstack(map(np.ravel, mesh))[0]
    
    in_convex_hull = np.logical_and(np.logical_and(x_delaunay.find_simplex(grid_points)>=0,
                                                   y_delaunay.find_simplex(grid_points)>=0),
                                    z_delaunay.find_simplex(grid_points)>=0)
    print grid_points.shape
    grid_points = grid_points[in_convex_hull]
    print grid_points.shape
    return grid_points

In [253]:
grid_points = mesh_bounded_by_convex_hulls(bounds, points, 0.003)

(830584, 3)
(488, 3)


In [254]:
def interpolate(grid_points, vector_points, vector_values):
    interpolated_data_x = griddata(vector_points[0], vector_values[0], grid_points)
    interpolated_data_y = griddata(vector_points[1], vector_values[1], grid_points)
    interpolated_data_z = griddata(vector_points[2], vector_values[2], grid_points)
    return interpolated_data_x, interpolated_data_y, interpolated_data_z

In [261]:
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(grid_points[:,0], grid_points[:,1], grid_points[:,2])
plt.show()

In [257]:
interpolated_vector = interpolate(grid_points, points, values)

In [259]:
interpolated_vector[0].shape

(488,)

In [187]:
def write_to_vtk(grid_point, interpolated_vector):
    

IndentationError: expected an indented block (<ipython-input-187-7b39104494de>, line 2)

In [297]:
(x_min, x_max), (y_min, y_max), (z_min, z_max) = bounds
    
x_delaunay = Delaunay(points[0])
y_delaunay = Delaunay(points[1])
z_delaunay = Delaunay(points[2])
    
x_coord = np.linspace(x_min, x_max, np.ceil((x_max-x_min)/spatial_increment))
y_coord = np.linspace(y_min, y_max, np.ceil((y_max-y_min)/spatial_increment))
z_coord = np.linspace(z_min, z_max, np.ceil((z_max-z_min)/spatial_increment))

mesh = np.meshgrid(x_coord, y_coord, z_coord)
    
grid_points = np.dstack(map(np.ravel, mesh))[0]
    
in_convex_hull = np.logical_and(np.logical_and(x_delaunay.find_simplex(grid_points)>=0,
                                                y_delaunay.find_simplex(grid_points)>=0),
                                z_delaunay.find_simplex(grid_points)>=0)

In [298]:
grid_points.shape

(830584, 3)

In [299]:
points[0].shape

(5114, 3)

In [300]:
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(points[0][:,0], points[0][:,1], points[0][:,2])
plt.show()

In [301]:
x_delaunay = Delaunay(points[0])

In [304]:
grid_points

array([[-0.032     , -0.032     , -0.032     ],
       [-0.032     , -0.032     , -0.0289785 ],
       [-0.032     , -0.032     , -0.02595699],
       ..., 
       [ 0.249     ,  0.249     ,  0.24295699],
       [ 0.249     ,  0.249     ,  0.24597849],
       [ 0.249     ,  0.249     ,  0.249     ]])

In [321]:
test = x_delaunay.find_simplex(grid_points, bruteforce=True, tol=1e-1)>=0

In [319]:
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(grid_points[test][:,0], grid_points[test][:,1], grid_points[test][:,2])
plt.show()

In [289]:
x_delaunay.convex_hull.astype(float)

array([[ 4945.,  4774.,  4777.],
       [ 4945.,  4987.,  4777.],
       [ 4234.,   531.,   223.],
       ..., 
       [  674.,   655.,   511.],
       [  674.,   678.,   667.],
       [  674.,   667.,   655.]])