In [154]:
import scipy.io.idl as idl
import numpy as np
from scipy.interpolate import griddata
import idl_plane_to_structured_vtk as idl_to_vtk

In [153]:
from pyvisfile.vtk import write_structured_grid

import numpy as np

angle_mesh = np.mgrid[1:2:10j, 0:2*np.pi:20j, 0:np.pi:30j]

r = angle_mesh[0, np.newaxis]
phi = angle_mesh[1, np.newaxis]
theta = angle_mesh[2, np.newaxis]
mesh = np.vstack((
    r*np.sin(theta)*np.cos(phi),
    r*np.sin(theta)*np.sin(phi),
    r*np.cos(theta),
    ))

from pytools.obj_array import make_obj_array
vec = make_obj_array([
    np.sin(theta)*np.cos(phi),
    np.sin(theta)*np.sin(phi),
    np.cos(theta),
    ])

print 'mesh', mesh.shape
print 'data', phi.shape
print 'r', r.shape

write_structured_grid("yo1.vts", mesh,
        point_data=[("phi", phi), ("vec", vec)])

mesh (3, 10, 20, 30)
data (1, 10, 20, 30)
r (1, 10, 20, 30)


RuntimeError: output file 'yo1.vts' already exists

# Try to store a single time from Jason's IDL scripts
Store $\vec{B}$, $T$, and $n$.

In [12]:
b_x_measurement_points_timestamp = '115110949362'
b_y_measurement_points_timestamp = '115110949522'
b_z_measurement_points_timestamp = '115110938869'
triple_measurement_points_timestamp = '115112535917'
b_x_measurements_timestamp = '115112539367'
b_y_measurements_timestamp = '115112539384'
b_z_measurements_timestamp = '115112539331'
n_measurements_timestamp = '115112539443'
t_measurements_timestamp = '115112539427'

In [13]:
data_path = '../../cataloging_physics_quantities/output/intermediate/'
data_ending = '.sav'
b_x_measurement_points_file = data_path + b_x_measurement_points_timestamp + data_ending
b_y_measurement_points_file = data_path + b_y_measurement_points_timestamp + data_ending
b_z_measurement_points_file = data_path + b_z_measurement_points_timestamp + data_ending
triple_measurement_points_file = data_path + triple_measurement_points_timestamp + data_ending 
b_x_measurements_file = data_path + b_x_measurements_timestamp + data_ending
b_y_measurements_file = data_path + b_y_measurements_timestamp + data_ending
b_z_measurements_file = data_path + b_z_measurements_timestamp + data_ending
n_measurements_file = data_path + n_measurements_timestamp + data_ending
t_measurements_file = data_path + t_measurements_timestamp + data_ending

In [14]:
b_x_measurement_points = idl.readsav(b_x_measurement_points_file)
b_y_measurement_points = idl.readsav(b_y_measurement_points_file)
b_z_measurement_points = idl.readsav(b_z_measurement_points_file)
triple_measurement_points =  idl.readsav(triple_measurement_points_file)
b_x_measurements = idl.readsav(b_x_measurements_file)
b_y_measurements = idl.readsav(b_y_measurements_file)
b_z_measurements = idl.readsav(b_z_measurements_file)
n_measurements = idl.readsav(n_measurements_file)
t_measurements = idl.readsav(t_measurements_file)

In [61]:
n_resampled, x_grid, y_grid = resample_on_structutred_grid(n_measurements, 0)

In [65]:
mesh = prepare_mesh(x_grid, y_grid, 0.25)

In [66]:
n_prepared = prepare_scalar(n_resampled)

In [68]:
write_to_structured_grid('../output/density2.vts', n_prepared, 'n', mesh)

In [69]:
print 'mesh', mesh.shape
print 'data', n_prepared.shape 

mesh (3, 100, 100, 1)
data (1, 100, 100, 1)


In [138]:
t_resampled, x_grid, y_grid = resample_on_structutred_grid(t_measurements, 0, to_clip=[0, 94, 0, 94])

In [139]:
mesh = prepare_mesh(x_grid, y_grid, 0.25)

In [140]:
t_prepared = prepare_scalar(t_resampled)

In [141]:
write_to_structured_grid('../output/temperatur6.vts', t_prepared, 't', mesh)

In [142]:
t_resampled.shape

(94, 94)

In [149]:
b_x_resampled, x_grid, y_grid = resample_on_structutred_grid(b_x_measurements, 0)
b_y_resampled, x_grid, y_grid = resample_on_structutred_grid(b_x_measurements, 0)
b_z_resampled, x_grid, y_grid = resample_on_structutred_grid(b_x_measurements, 0)

In [150]:
np.where(np.isnan(b_x_resampled))

(array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,
         2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,
         4,  4,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,
         5,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  7,  7,  8,
         8,  8,  8,  8,  8,  9,  9,  9,  9,  9, 10, 10, 10, 10, 11, 11, 11,
        12, 12, 13, 91, 92, 92, 93, 93, 93, 94, 94, 94, 94, 95, 95, 95, 95,
        95, 96, 96, 96, 96, 96, 96, 97, 97, 97, 97, 97, 97, 97, 98, 98, 98,
        98, 98, 98, 98, 98]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13,  0,  1,  2,
         3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  0,  1,  2,  3,  4,  5,  6,
         7,  8,  9, 10, 11,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  0,
         1,  2,  3,  4,  5,  6,  7,  8,  9,  0,  1,  2,  3,  4,  5,  6,  7,
         8,  0,  1,  2,  3,  4,  5,  6,  7,  0,  1,  2,  3

In [148]:
b_x_resampled

(array([[             nan,              nan,              nan, ...,
           1.19409625e-04,   1.16660935e-04,   1.13912246e-04],
        [             nan,              nan,              nan, ...,
          -9.74559990e-06,  -3.52371282e-05,  -6.07286565e-05],
        [             nan,              nan,              nan, ...,
          -2.07129267e-04,  -2.32620795e-04,  -2.58112324e-04],
        ..., 
        [             nan,              nan,              nan, ...,
          -1.73300701e-04,  -1.38142752e-04,  -1.02984803e-04],
        [             nan,              nan,              nan, ...,
          -1.75282231e-04,  -1.46369746e-04,  -1.21999279e-04],
        [             nan,              nan,              nan, ...,
          -1.71169648e-04,  -1.46799181e-04,  -1.22428714e-04]]),
 array([[-0.032     , -0.03142424, -0.03084849, ...,  0.02327273,
          0.02384849,  0.02442424],
        [-0.032     , -0.03142424, -0.03084849, ...,  0.02327273,
          0.02384849,  0