# Getting data into VTK files for VisIt

In this noteboook I adapt an unstructured grid example for the pyvisfile library to save data from Jason's IDL scripts.

In [1]:
import numpy as np
from pyvisfile.vtk import ( 
    UnstructuredGrid, DataArray,
    AppendedDataXMLGenerator,
    VTK_VERTEX, VF_LIST_OF_VECTORS, VF_LIST_OF_COMPONENTS)

n = 5000
points = np.random.randn(n, 3)

data = [
        ("p", np.random.randn(n)),
        ("vel", np.random.randn(3, n)),
]
file_name = "points.vtu"
compressor = None

grid = UnstructuredGrid(
        (n, DataArray("points", points, vector_format=VF_LIST_OF_VECTORS)),
        cells=np.arange(n, dtype=np.uint32),
        cell_types=np.asarray([VTK_VERTEX] * n, dtype=np.uint8))

for name, field in data:
    grid.add_pointdata(DataArray(name, field,
        vector_format=VF_LIST_OF_COMPONENTS))

from os.path import exists
if exists(file_name):
    raise RuntimeError("output file '%s' already exists"
        % file_name)

outf = open(file_name, "w")
AppendedDataXMLGenerator(compressor)(grid).write(outf)
outf.close()

# Try to store a single time from Jason's IDL scripts
Store $\vec{B}$, $T$, and $n$.

In [6]:
b_x_measurement_points_timestamp = '115110949362'
b_y_measurement_points_timestamp = '115110949522'
b_z_measurement_points_timestamp = '115110938869'
triple_measurement_points_timestamp = '115112535917'
b_x_measurements_timestamp = '115112539367'
b_y_measurements_timestamp = '115112539384'
b_z_measurements_timestamp = '115112539331'
n_measurements_timestamp = '115112539443'
t_measurements_timestamp = '115112539427'

In [7]:
data_path = '../../cataloging_physics_quantities/output/intermediate/'
data_ending = '.sav'
b_x_measurement_points_file = data_path + b_x_measurement_points_timestamp + data_ending
b_y_measurement_points_file = data_path + b_y_measurement_points_timestamp + data_ending
b_z_measurement_points_file = data_path + b_z_measurement_points_timestamp + data_ending
triple_measurement_points_file = data_path + triple_measurement_points_timestamp + data_ending 
b_x_measurements_file = data_path + b_x_measurements_timestamp + data_ending
b_y_measurements_file = data_path + b_y_measurements_timestamp + data_ending
b_z_measurements_file = data_path + b_z_measurements_timestamp + data_ending
n_measurements_file = data_path + n_measurements_timestamp + data_ending
t_measurements_file = data_path + t_measurements_timestamp + data_ending

In [4]:
import scipy.io.idl as idl

In [ ]:
def convert_scalar_idl_sav_to_vtk(scalar_measurements_points_file, 
                                  scalar_measurements_file):
    r"""
    Read IDL sav files and store in a vtk file.
    """
    scalar_measurements_points = idl.readsav(scalar_measurements_points_file, 
                                             verbose=False)
    scalar_measurements = idl.readsav(scalar_measurements_file, 
                                      verbose=False)
    

In [29]:
b_x_measurement_points = idl.readsav(b_x_measurement_points_file)

In [30]:
b_y_measurement_points = idl.readsav(b_y_measurement_points_file)

In [34]:
np.allclose(b_x_measurement_points['x_out'], b_y_measurement_points['x_out'])

ValueError: operands could not be broadcast together with shapes (755,) (2104,) 

In [33]:
b_y_measurement_points['x_out']

array([-0.032, -0.032, -0.032, ...,  0.025,  0.025,  0.025], dtype=float32)

In [20]:
measurements = idl.readsav(n_measurements_file)

In [15]:
measurement_points['x_out']

array([-0.024, -0.024, -0.024, -0.024, -0.024, -0.024, -0.024, -0.024,
       -0.024, -0.024, -0.024, -0.024, -0.024, -0.024, -0.024, -0.024,
       -0.024, -0.024, -0.024, -0.024, -0.024, -0.024, -0.024, -0.024,
       -0.024, -0.024, -0.024, -0.024, -0.024, -0.024, -0.024, -0.024,
       -0.024, -0.024, -0.024, -0.024, -0.024, -0.024, -0.024, -0.024,
       -0.024, -0.024, -0.024, -0.024, -0.024, -0.024, -0.024, -0.024,
       -0.024, -0.024, -0.024, -0.024, -0.024, -0.024, -0.024, -0.024,
       -0.024, -0.024, -0.024, -0.024, -0.024, -0.024, -0.024, -0.024,
       -0.024, -0.024, -0.024, -0.024, -0.024, -0.024, -0.024, -0.024,
       -0.024, -0.021, -0.021, -0.021, -0.021, -0.021, -0.021, -0.021,
       -0.021, -0.021, -0.021, -0.021, -0.021, -0.021, -0.021, -0.021,
       -0.021, -0.021, -0.021, -0.021, -0.021, -0.021, -0.021, -0.021,
       -0.021, -0.021, -0.021, -0.021, -0.021, -0.021, -0.021, -0.021,
       -0.021, -0.021, -0.021, -0.021, -0.021, -0.021, -0.021, -0.021,
      

In [16]:
measurement_points['y_out']

array([ 0.055,  0.055,  0.055,  0.055,  0.055,  0.055,  0.055,  0.055,
        0.055,  0.055,  0.055,  0.055,  0.055,  0.055,  0.055,  0.055,
        0.055,  0.055,  0.055,  0.055,  0.055,  0.052,  0.049,  0.049,
        0.046,  0.046,  0.046,  0.043,  0.043,  0.04 ,  0.04 ,  0.037,
        0.037,  0.034,  0.034,  0.031,  0.025,  0.022,  0.019,  0.016,
        0.013,  0.013,  0.013,  0.013,  0.013,  0.013,  0.013,  0.022,
        0.019,  0.016,  0.013,  0.01 ,  0.007,  0.004,  0.004,  0.001,
       -0.002, -0.005, -0.008, -0.011, -0.014, -0.017, -0.02 , -0.023,
       -0.026, -0.029, -0.032, -0.035, -0.038, -0.041, -0.044, -0.047,
       -0.05 ,  0.05 ,  0.047,  0.044,  0.041,  0.038,  0.035,  0.032,
        0.029,  0.026,  0.023,  0.02 ,  0.017,  0.014,  0.011,  0.008,
        0.005,  0.002, -0.001, -0.004, -0.007, -0.01 , -0.013, -0.016,
       -0.019, -0.022, -0.025, -0.028, -0.031, -0.034, -0.037, -0.04 ,
       -0.049, -0.043, -0.046,  0.05 ,  0.05 ,  0.05 ,  0.05 ,  0.05 ,
      